bind_host: 0.0.0.0
bind_port: 5000
users:
  - name: 
    password: 
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: en
theme: light
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
    - 127.0.0.1
    - 10.0.1.1
    - 10.0.2.1
    - 10.0.3.1
    - 10.0.4.1
  port: 53
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: null_ip
  blocking_ipv4: 
  blocking_ipv6: 
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 100
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - '[//lan/local/]127.0.0.1:553'
    - h3://1.1.1.1/dns-query
    - h3://1.0.0.1/dns-query
    - quic://dns1.nextdns.io
    - quic://dns2.nextdns.io
  upstream_dns_file: ""
  bootstrap_dns:
    - 1.1.1.1
    - 1.0.0.1
  all_servers: true
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients:
    - 127.0.0.1
    - 10.0.1.0/24
    - 10.0.2.0/24
    - 10.0.3.0/24
    - 10.0.4.0/24
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
    - wpad.lan
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 100000000
  cache_ttl_min: 1000
  cache_ttl_max: 100000
  cache_optimistic: true
  bogus_nxdomain: []
  aaaa_disabled: true
  enable_dnssec: false
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams:
    - 127.0.0.1:553
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
tls:
  enabled: true
  server_name: 
  force_https: false
  port_https: 5001
  port_dns_over_tls: 853
  port_dns_over_quic: 0
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: 
  private_key_path: 
  strict_sni_check: false
querylog:
  enabled: true
  file_enabled: true
  interval: 168h
  size_memory: 1000
  ignored: []
statistics:
  enabled: true
  interval: 30
  ignored: []
filters:
  - enabled: true
    url: https://gist.githubusercontent.com/BBcan177/4a8bf37c131be4803cb2/raw
    name: BBcan177
    id: 1637157503
  - enabled: true
    url: https://raw.githubusercontent.com/elliotwutingfeng/Inversion-DNSBL-Blocklists/main/Google_hostnames_ABP.txt
    name: ElliotWutingFeng
    id: 1659546812
  - enabled: true
    url: https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh-online.txt
    name: Online Malicious URL Blocklist
    id: 1660941695
  - enabled: true
    url: https://v.firebog.net/hosts/static/w3kbl.txt
    name: WaLLy3K (Personal)
    id: 1664659183
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt
    name: OISD Blocklist Full
    id: 1671872732
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt
    name: Peter Lowe's Blocklist
    id: 1671872734
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1671872735
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt
    name: Scam Blocklist by DurableNapkin
    id: 1671872742
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt
    name: Dandelion Sprout's Anti-Malware List
    id: 1671872743
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
    name: Malicious URL Blocklist (URLHaus)
    id: 1671872744
  - enabled: true
    url: https://raw.githubusercontent.com/elliotwutingfeng/GlobalAntiScamOrg-blocklist/main/global-anti-scam-org-scam-urls-ABP.txt
    name: Global Anti Scam Org
    id: 1674637811
  - enabled: true
    url: https://hblock.molinero.dev/hosts_adblock.txt
    name: hBlock
    id: 1674637812
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt
    name: Dan Pollock's List
    id: 1674637813
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt
    name: Steven Black's List
    id: 1674637814
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    name: AdAway Default Blocklist
    id: 1674637815
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_32.txt
    name: The NoTracking blocklist
    id: 1674637816
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt
    name: 1Hosts (Lite)
    id: 1674637817
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt
    name: Phishing URL Blocklist (PhishTank and OpenPhish)
    id: 1674637818
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt
    name: The Big List of Hacked Malware Web Sites
    id: 1674637819
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt
    name: WindowsSpyBlocker - Hosts spy rules
    id: 1674637820
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt
    name: NoCoin Filter List
    id: 1674637821
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_31.txt
    name: Stalkerware Indicators List
    id: 1674637822
  - enabled: true
    url: https://nocdn.nrd-list.com/1/nrd-list-7-days.txt
    name: NRD-List (7 Days)
    id: 1675335573
  - enabled: true
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds.txt
    name: HaGeZi (Most Abused TLDs)
    id: 1675418341
  - enabled: true
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.txt
    name: HaGeZi  (Pro++)
    id: 1675418342
  - enabled: true
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt
    name: HaGeZi (Threat Intelligence Feeds)
    id: 1675418343
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_34.txt
    name: HaGeZi Personal Black & White
    id: 1675418345
  - enabled: true
    url: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
    name: Lightswitch05
    id: 1675418348
  - enabled: true
    url: https://github.com/kiwilad-nz/AdguardHome/raw/main/Deny/agh-regex-denylist
    name: KiwiLAD (Regex)
    id: 1675418363
  - enabled: true
    url: https://github.com/kiwilad-nz/AdguardHome/raw/main/Deny/agh-tld-denylist
    name: KiwiLAD (TLD)
    id: 1675418364
  - enabled: true
    url: https://raw.githubusercontent.com/TheAntiSocialEngineer/AntiSocial-BlockList-UK-Community/main/UK-Community.txt
    name: TheAntiSocialEngineer
    id: 1676483509
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt
    name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
    id: 1676544103
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_6.txt
    name: Dandelion Sprout's Game Console Adblock List
    id: 1676544104
  - enabled: true
    url: https://raw.githubusercontent.com/slyfox1186/pihole-regex/main/domains/blacklist/regex-blacklist.txt
    name: Slyfox1186 (Regex)
    id: 1676544106
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_38.txt
    name: 1Hosts (mini)
    id: 1676996641
  - enabled: true
    url: https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock
    name: d3ward
    id: 1678383955
  - enabled: true
    url: https://o0.pages.dev/Pro/adblock.txt
    name: 1Hosts (Pro)
    id: 1678383956
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_5.txt
    name: OISD Blocklist Basic
    id: 1678383957
  - enabled: true
    url: https://github.com/kiwilad-nz/AdguardHome/raw/main/Deny/agh-dns-denylist
    name: KiwiLAD (DNS)
    id: 1678383958
  - enabled: true
    url: https://github.com/kiwilad-nz/AdguardHome/raw/main/Deny/agh-hosts-denylist
    name: KiwiLAD (Hosts)
    id: 1678383960
whitelist_filters:
  - enabled: true
    url: https://raw.githubusercontent.com/im-sm/Pi-hole-Torrent-Blocklist/main/all-torrent-trackres.txt
    name: Sakib Mahmud (Torrent Trackers)
    id: 1660941699
  - enabled: true
    url: https://raw.githubusercontent.com/boutetnico/url-shorteners/master/list.txt
    name: Boutetnico (URL-Shorteners)
    id: 1663189370
  - enabled: true
    url: https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/referral-sites.txt
    name: AnudeepND (Referral-Sites)
    id: 1663189375
  - enabled: true
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist.txt
    name: HaGeZi
    id: 1663189378
  - enabled: true
    url: https://raw.githubusercontent.com/TheSmashy/O365Whitlist/main/domains/whitelist.txt
    name: TheSmashy (O365)
    id: 1663189381
  - enabled: true
    url: https://raw.githubusercontent.com/nextdns/click-tracking-domains/main/domains
    name: NextDNS (Affiliate Links)
    id: 1663189391
  - enabled: true
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt
    name: HaGeZi (Referral)
    id: 1663189425
  - enabled: true
    url: https://blocklistproject.github.io/Lists/torrent.txt
    name: TheBlocklistProject (Torrent)
    id: 1675418331
  - enabled: true
    url: https://github.com/nextdns/piracy-blocklists/raw/master/torrent-trackers
    name: NextDNS (Torrent Trackers)
    id: 1675418349
  - enabled: true
    url: https://github.com/nextdns/piracy-blocklists/raw/master/torrent-clients
    name: NextDNS (Torrent Clients)
    id: 1675418350
  - enabled: true
    url: https://github.com/nextdns/piracy-blocklists/raw/master/file-hosting
    name: NextDNS (File Hosting)
    id: 1675418351
  - enabled: true
    url: https://github.com/kiwilad-nz/AdguardHome/raw/main/Allow/agh-hosts-allowlist
    name: KiwiLAD (Hosts)
    id: 1675418357
  - enabled: true
    url: https://github.com/kiwilad-nz/AdguardHome/raw/main/Allow/agh-regex-allowlist
    name: KiwiLAD (Regex)
    id: 1678383959
user_rules:
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent:
    - name: Flat_DHCP
      tags: []
      ids:
        - 10.0.3.128/25
      blocked_services: []
      upstreams: []
      use_global_settings: false
      filtering_enabled: false
      parental_enabled: false
      safesearch_enabled: false
      safebrowsing_enabled: false
      use_global_blocked_services: false
    - name: Home_DHCP
      tags: []
      ids:
        - 10.0.2.128/25
      blocked_services: []
      upstreams: []
      use_global_settings: true
      filtering_enabled: false
      parental_enabled: false
      safesearch_enabled: false
      safebrowsing_enabled: false
      use_global_blocked_services: true
    - name: pfSense.lan
      tags: []
      ids:
        - 127.0.0.1
      blocked_services: []
      upstreams: []
      use_global_settings: false
      filtering_enabled: false
      parental_enabled: false
      safesearch_enabled: false
      safebrowsing_enabled: false
      use_global_blocked_services: false
log_file: ""
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_compress: false
log_localtime: false
verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 17
